### ISSUE TITLE
Colore ciano poco leggibile nella tabella dei contenuti

### ISSUE THREAD

**Issue by francescobozzo** [ZamboniM/Analisi1-UNITN#2]
Proporrei di utilizzare un colore nero standard per l'indice, seppur esso sia composto da link interni. Penso ne migliorerebbe la leggibilità.

**Comment by ghost** [comment]
Reimpostato il colore di default dei link interni a nero; in questo modo l'indice sarà di questo colore. Gli altri link però continueranno ad essere colorati (a mano di volta in volta) per chiarezza
